spring.application.name=api-igreja

spring.datasource.url=jdbc:mysql://localhost:3306/igreja_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=adaware2972
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true