spring.application.name=api-igreja

spring-jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=igreja_db_v9bk_user
spring. datasource.password=1TgD6aAbpfqy2j7o8L8g0NXHM3GZk6ue
spring.datasource.url=jdbc:postgresql://dpg-dak06lrm8hqs739v7ul0-a:5432/igreja_db_v9bk
spring-jpa.generate-ddl=true
spring-jpa.hibernate.ddl-auto=update
spring-jpa.show-sql=true
